#!/bin/bash
#SBATCH -N 2
#SBATCH -n 96
#SBATCH -o pi.script.log
#SBATCH -J pi_estimation
#SBATCH -p skx-normal
#SBATCH -t 00:15:00

module purge 
module load TACC
module load launcher

export LAUNCHER_PLUGIN_DIR=$LAUNCHER_DIR/plugins
export LAUNCHER_RMI=SLURM
export LAUNCHER_JOB_FILE=./jobfile_pi

$LAUNCHER_DIR/paramrun
