#!/bin/bash
start=$(date +%s)
pi=3.1415926535
error=100
iteration=1
N_chunk=100
num_samples=0
num_i=0

check=$(bc -l <<< "$error > 0.01")
echo $check
while [ $check == 1 ]
do
	
	iteration=$(($iteration+1))
	num_samples=$(($num_samples+$N_chunk))
	read N_samples N_i N_o pi_estimate nothing_error <<< $(./pi.complied 100 $i)
	num_i=$(($N_i+$num_i))
	new_pi=$(bc -l <<< "(4*$num_i)/$num_samples") 
	middle=$(bc -l <<< "$new_pi - $pi")
	error=$(bc -l <<< "sqrt($middle*$middle)/$pi")
	check=$(bc -l <<< "$error > 0.01")
	end=$(date +%s)
	run_time=$(($end-$start))
	echo $iteration $num_samples
	echo "iter: $iteration  num_samples: $num_samples  num_i: $num_i  pi: $new_pi  relative_error: $error  time_accum: $run_time" >> iter.log
done   
	







